export default [
  {
    files: ["*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        // p5.js globals
        width: "readonly", height: "readonly", frameCount: "readonly", mouseX: "readonly", mouseY: "readonly",
        key: "readonly", keyCode: "readonly", keyIsDown: "readonly",
        PI: "readonly", TWO_PI: "readonly", HALF_PI: "readonly",
        LEFT_ARROW: "readonly", RIGHT_ARROW: "readonly", UP_ARROW: "readonly", DOWN_ARROW: "readonly",
        SHIFT: "readonly", ENTER: "readonly", CENTER: "readonly", CORNER: "readonly",
        LEFT: "readonly", RIGHT: "readonly", TOP: "readonly", BOTTOM: "readonly",
        BLEND: "readonly", CLOSE: "readonly", PIE: "readonly", ITALIC: "readonly", NORMAL: "readonly",
        fill: "readonly", noFill: "readonly", stroke: "readonly", noStroke: "readonly", strokeWeight: "readonly",
        rect: "readonly", ellipse: "readonly", circle: "readonly", line: "readonly", triangle: "readonly", arc: "readonly",
        beginShape: "readonly", endShape: "readonly", vertex: "readonly",
        push: "readonly", pop: "readonly", translate: "readonly", rotate: "readonly", scale: "readonly",
        text: "readonly", textSize: "readonly", textAlign: "readonly", textStyle: "readonly",
        color: "readonly", red: "readonly", green: "readonly", blue: "readonly", lerp: "readonly", lerpColor: "readonly",
        map: "readonly", constrain: "readonly", dist: "readonly", abs: "readonly", floor: "readonly", ceil: "readonly",
        min: "readonly", max: "readonly", round: "readonly", sqrt: "readonly", pow: "readonly", nf: "readonly",
        sin: "readonly", cos: "readonly", atan2: "readonly", random: "readonly", randomSeed: "readonly",
        createCanvas: "readonly", windowWidth: "readonly", windowHeight: "readonly", millis: "readonly",
        drawingContext: "readonly", tint: "readonly", noTint: "readonly", image: "readonly", loadImage: "readonly",
        p5: "readonly", getAudioContext: "readonly",
        // Game globals
        state: "writable", cam: "writable", camSmooth: "writable", snd: "writable",
        gameScreen: "writable", menuHover: "writable", menuFadeIn: "writable", menuKeyIdx: "writable",
        menuFadeOut: "writable", menuFadeAction: "writable", menuBgImg: "writable",
        particles: "writable", floatingText: "writable", floatOffset: "writable", horizonOffset: "writable",
        shakeX: "writable", shakeY: "writable", shakeTimer: "writable",
        dialogState: "writable", photoMode: "writable", empireDashOpen: "writable", inventoryOpen: "writable",
        screenTransition: "writable", achievementPopup: "writable", tutorialHint: "writable",
        notifications: "writable", lightningBolts: "writable", stormTimer: "writable", stormActive: "writable", weatherTransition: "writable",
        starPositions: "writable", cloudPositions: "writable", skyBirds: "writable", seasonLeaves: "writable",
        hudFlash: "writable", energyArcs: "writable", _harvestArcs: "writable", _catchCard: "writable", _codexNewEntries: "writable",
        WORLD: "readonly", WRECK: "readonly", C: "readonly", BLUEPRINTS: "readonly",
        HOTBAR_ITEMS: "readonly", WEAPONS: "readonly", ARMORS: "readonly",
        // Cross-file functions
        w2sX: "readonly", w2sY: "readonly", s2wX: "readonly", s2wY: "readonly",
        getSurfaceRX: "readonly", getSurfaceRY: "readonly", getFarmCenterX: "readonly", getFarmCenterY: "readonly",
        isOnIsland: "readonly", isInShallows: "readonly", isWalkable: "readonly", isOnBridge: "readonly",
        addFloatingText: "readonly", spawnParticles: "readonly", triggerScreenShake: "readonly",
        addNotification: "readonly", showAchievement: "readonly", unlockJournal: "readonly",
        spawnHarvestArc: "readonly", updateHarvestArcs: "readonly", drawHarvestArcs: "readonly",
        markCodexDiscovery: "readonly", isCodexEntryNew: "readonly", _drawNatEntryWithDiscovery: "readonly",
        showCatchCard: "readonly", updateCatchCard: "readonly", drawCatchCard: "readonly",
        getPortPosition: "readonly", getMerchantPortPosition: "readonly", updateWeatherTransition: "readonly", drawWeatherTransitionEffects: "readonly",
        getSkyBrightness: "readonly", getSeason: "readonly", getSeasonName: "readonly", getFestival: "readonly",
        drawParchmentPanel: "readonly", drawHUDPanel: "readonly",
        saveGame: "readonly", loadGame: "readonly", startNewGame: "readonly", startLoadGame: "readonly",
        trackMilestone: "readonly", updatePortPositions: "readonly",
        // Functions from other modules
        drawMenuScreen: "readonly", handleMenuClick: "readonly", drawSettingsPanel: "readonly", drawCreditsPanel: "readonly",
        drawIntroCinematic: "readonly", skipIntro: "readonly", skipCutscene: "readonly",
        startSailingCutscene: "readonly", startPreRepairCutscene: "readonly", completeSailToHome: "readonly",
        updateMainQuest: "readonly", updateNPCQuests: "readonly", advanceMainQuestCounter: "readonly",
        advanceNPCQuestCounter: "readonly", initNarrativeState: "readonly", checkLoreTabletPickup: "readonly",
        updateNarrativeDialogue: "readonly", getExpandedDialogue: "readonly", getMaxHeartsDialogue: "readonly", tickPendingNudges: "readonly",
        grantXP: "readonly", updateCombatSystem: "readonly", drawCombatOverlay: "readonly",
        handleCombatSkillKey: "readonly", tryDodgeRoll: "readonly", toggleSkillTree: "readonly",
        handleSkillTreeClick: "readonly", drawSkillTree: "readonly", skillTreeOpen: "writable",
        getHarvestSkillBonus: "readonly", getFishingLuckBonus: "readonly", getCompanionRegenBonus: "readonly",
        updateEconomySystem: "readonly", drawEconomyWorldOverlay: "readonly", drawEconomyUIOverlay: "readonly",
        handleEconomyKey: "readonly", handleEconomyClick: "readonly", onDayTransitionEconomy: "readonly",
        startDive: "readonly", exitDive: "readonly", updateDiving: "readonly", drawDivingOverlay: "readonly", drawDivePrompt: "readonly",
        enterVulcan: "readonly", exitVulcan: "readonly", enterHyperborea: "readonly", enterPlenty: "readonly", enterNecropolis: "readonly",
        enterVulcanContent: "readonly", enterHyperboreContent: "readonly", enterPlentyContent: "readonly", enterNecropolisContent: "readonly",
        _isExplorationActive: "readonly",
        isOnImperialBridge: "readonly", Debug: "readonly",
        console: "readonly", document: "readonly", window: "readonly", localStorage: "readonly", setTimeout: "readonly", setInterval: "readonly",
      },
    },
    rules: {
      "no-undef": "warn",
      "no-unused-vars": "off",
      "no-redeclare": "warn",
      "no-constant-condition": "off",
      "no-empty": "off",
    },
  },
  {
    ignores: ["node_modules/**", "dist/**", "sw.js"],
  },
];
